-*- mode: restclient-mode; -*-
:host = http://localhost:8080
:lobby-id = 12
:jwt =
#^ valid jwt needed

# Root
GET :host/
Cookie: auth-jwt=:jwt;

# view jwt user info
GET :host/user
Cookie: auth-jwt=:jwt;

# lobby
GET :host/lobby/12
Cookie: auth-jwt=:jwt;
